-- Common helper functions
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================================
-- 1. sites Table
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.sites (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    jwks_url VARCHAR(255) NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.sites_deleted (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    old_data JSONB NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION public.sites_deleted_fn()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.sites_deleted (old_data, deleted_at)
  VALUES (to_jsonb(OLD), CURRENT_TIMESTAMP);
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER sites_deleted_trigger
AFTER DELETE ON public.sites
FOR EACH ROW
EXECUTE FUNCTION public.sites_deleted_fn();

CREATE OR REPLACE TRIGGER update_sites_updated_at
BEFORE UPDATE ON public.sites
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- =========================================================================
-- 2. users Table
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    avatar VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.users_deleted (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    old_data JSONB NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION public.users_deleted_fn()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users_deleted (old_data, deleted_at)
  VALUES (to_jsonb(OLD), CURRENT_TIMESTAMP);
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER users_deleted_trigger
AFTER DELETE ON public.users
FOR EACH ROW
EXECUTE FUNCTION public.users_deleted_fn();

CREATE OR REPLACE TRIGGER update_users_updated_at
BEFORE UPDATE ON public.users
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- =========================================================================
-- 3. user_cyanlys Table
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.user_cyanlys (
    user_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    is_superuser BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS public.user_cyanlys_deleted (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    old_data JSONB NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION public.user_cyanlys_deleted_fn()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.user_cyanlys_deleted (old_data, deleted_at)
  VALUES (to_jsonb(OLD), CURRENT_TIMESTAMP);
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER user_cyanlys_deleted_trigger
AFTER DELETE ON public.user_cyanlys
FOR EACH ROW
EXECUTE FUNCTION public.user_cyanlys_deleted_fn();

CREATE OR REPLACE TRIGGER update_user_cyanlys_updated_at
BEFORE UPDATE ON public.user_cyanlys
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- =========================================================================
-- 4. user_sites Table
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.user_sites (
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    site_id VARCHAR(255) REFERENCES public.sites(id) ON DELETE CASCADE,
    permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
    PRIMARY KEY (user_id, site_id)
);

CREATE TABLE IF NOT EXISTS public.user_sites_deleted (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    old_data JSONB NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION public.user_sites_deleted_fn()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.user_sites_deleted (old_data, deleted_at)
  VALUES (to_jsonb(OLD), CURRENT_TIMESTAMP);
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER user_sites_deleted_trigger
AFTER DELETE ON public.user_sites
FOR EACH ROW
EXECUTE FUNCTION public.user_sites_deleted_fn();

-- =========================================================================
-- 5. user_sessions Table
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.user_sessions (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    refresh_token_jti VARCHAR(255) UNIQUE NOT NULL,
    device_name VARCHAR(255) NOT NULL,
    device_type VARCHAR(50) NOT NULL,
    user_agent TEXT NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_refresh_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.user_sessions_deleted (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    old_data JSONB NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION public.user_sessions_deleted_fn()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.user_sessions_deleted (old_data, deleted_at)
  VALUES (to_jsonb(OLD), CURRENT_TIMESTAMP);
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER user_sessions_deleted_trigger
AFTER DELETE ON public.user_sessions
FOR EACH ROW
EXECUTE FUNCTION public.user_sessions_deleted_fn();
